export const ZEME = [
    {
        value: 1,
        label: 'Základní rozdělení',
        children: [
            {value: 'EVR', label: 'Evropa'},
            {value: 'WRL', label: 'Svět bez USA, Kanady a Austrálie'},
            {value: 'ALL', label: 'Celý svět'}
        ]
    },
    {
        value: 2,
        label: 'Abecední seznam zemí',
        children: [
            {value: 'AFG', label: 'Afghánistán'},
            {value: 'ALB', label: 'Albánie'},
            {value: 'DZA', label: 'Alžírsko'},
            {value: 'AND', label: 'Andorra'},
            {value: 'AGO', label: 'Angola'},
            {value: 'AIA', label: 'Anguilla'},
            {value: 'ATA', label: 'Antarktida'},
            {value: 'ATG', label: 'Antigua a Barbuda'},
            {value: 'ARG', label: 'Argentina'},
            {value: 'ARM', label: 'Arménie'},
            {value: 'ABW', label: 'Aruba'},
            {value: 'AUS', label: 'Austrálie'},
            {value: 'AZE', label: 'Ázerbájdžán'},
            {value: 'BHS', label: 'Bahamy'},
            {value: 'BHR', label: 'Bahrajn'},
            {value: 'BGD', label: 'Bangladéš'},
            {value: 'BRB', label: 'Barbados'},
            {value: 'BEL', label: 'Belgie'},
            {value: 'BLZ', label: 'Belize'},
            {value: 'BLR', label: 'Bělorusko'},
            {value: 'BEN', label: 'Benin'},
            {value: 'BMU', label: 'Bermudy'},
            {value: 'BTN', label: 'Bhútán'},
            {value: 'BOL', label: 'Bolívie'},
            {value: 'BIH', label: 'Bosna a Hercegovina'},
            {value: 'BWA', label: 'Botswana'},
            {value: 'BRA', label: 'Brazílie'},
            {value: 'BRN', label: 'Brunej'},
            {value: 'BGR', label: 'Bulharsko'},
            {value: 'BFA', label: 'Burkina Faso'},
            {value: 'BDI', label: 'Burundi'},
            {value: 'COK', label: 'Cookovy ostrovy'},
            {value: 'TCD', label: 'Čad'},
            {value: 'MNE', label: 'Černá Hora'},
            {value: 'CHN', label: 'Čína'},
            {value: 'DNK', label: 'Dánsko'},
            {value: 'COD', label: 'Demokratická republika Kongo'},
            {value: 'DMA', label: 'Dominika'},
            {value: 'DOM', label: 'Dominikánská republika'},
            {value: 'DJI', label: 'Džibutsko'},
            {value: 'EGY', label: 'Egypt'},
            {value: 'ECU', label: 'Ekvádor'},
            {value: 'ERI', label: 'Eritrea'},
            {value: 'EST', label: 'Estonsko'},
            {value: 'ETH', label: 'Etiopie'},
            {value: 'FJI', label: 'Fidži'},
            {value: 'PHL', label: 'Filipíny'},
            {value: 'FIN', label: 'Finsko'},
            {value: 'FRA', label: 'Francie'},
            {value: 'GAB', label: 'Gabon'},
            {value: 'GMB', label: 'Gambie'},
            {value: 'GHA', label: 'Ghana'},
            {value: 'GIB', label: 'Gibraltar'},
            {value: 'GRD', label: 'Grenada'},
            {value: 'GRL', label: 'Grónsko'},
            {value: 'GEO', label: 'Gruzie'},
            {value: 'GTM', label: 'Guatemala'},
            {value: 'GIN', label: 'Guinea'},
            {value: 'GNB', label: 'Guinea-Bissau'},
            {value: 'GUY', label: 'Guyana'},
            {value: 'HTI', label: 'Haiti'},
            {value: 'HND', label: 'Honduras'},
            {value: 'HKG', label: 'Hongkong'},
            {value: 'CHL', label: 'Chile'},
            {value: 'HRV', label: 'Chorvatsko'},
            {value: 'IND', label: 'Indie'},
            {value: 'IDN', label: 'Indonésie'},
            {value: 'IRQ', label: 'Irák'},
            {value: 'IRN', label: 'Írán'},
            {value: 'IRL', label: 'Irsko'},
            {value: 'ISL', label: 'Island'},
            {value: 'ITA', label: 'Itálie'},
            {value: 'ISR', label: 'Izrael'},
            {value: 'JAM', label: 'Jamajka'},
            {value: 'JPN', label: 'Japonsko'},
            {value: 'YEM', label: 'Jemen'},
            {value: 'ZAF', label: 'Jihoafrická republika'},
            {value: 'KOR', label: 'Jižní Korea'},
            {value: 'JOR', label: 'Jordánsko'},
            {value: 'CYM', label: 'Kajmanské ostrovy'},
            {value: 'KHM', label: 'Kambodža'},
            {value: 'CMR', label: 'Kamerun'},
            {value: 'CAN', label: 'Kanada'},
            {value: 'CPV', label: 'Kapverdy'},
            {value: 'QAT', label: 'Katar'},
            {value: 'KAZ', label: 'Kazachstán'},
            {value: 'KEN', label: 'Keňa'},
            {value: 'KIR', label: 'Kiribati'},
            {value: 'COL', label: 'Kolumbie'},
            {value: 'COM', label: 'Komory'},
            {value: 'COG', label: 'Kongo'},
            {value: 'CRI', label: 'Kostarika'},
            {value: 'CUB', label: 'Kuba'},
            {value: 'KWT', label: 'Kuvajt'},
            {value: 'CYP', label: 'Kypr'},
            {value: 'KGZ', label: 'Kyrgyzstán'},
            {value: 'LAO', label: 'Laos'},
            {value: 'LSO', label: 'Lesotho'},
            {value: 'LBN', label: 'Libanon'},
            {value: 'LBR', label: 'Libérie'},
            {value: 'LBY', label: 'Libye'},
            {value: 'LIE', label: 'Lichtenštejnsko'},
            {value: 'LTU', label: 'Litva'},
            {value: 'LVA', label: 'Lotyšsko'},
            {value: 'LUX', label: 'Lucembursko'},
            {value: 'MAC', label: 'Macao'},
            {value: 'MDG', label: 'Madagaskar'},
            {value: 'HUN', label: 'Maďarsko'},
            {value: 'MKD', label: 'Makedonie'},
            {value: 'MYS', label: 'Malajsie'},
            {value: 'MWI', label: 'Malawi'},
            {value: 'MDV', label: 'Maledivy'},
            {value: 'MLI', label: 'Mali'},
            {value: 'MLT', label: 'Malta'},
            {value: 'MAR', label: 'Maroko'},
            {value: 'MHL', label: 'Marshallovy ostrovy'},
            {value: 'MTQ', label: 'Martinik'},
            {value: 'MUS', label: 'Mauricius'},
            {value: 'MRT', label: 'Mauritánie'},
            {value: 'MEX', label: 'Mexiko'},
            {value: 'FSM', label: 'Mikronésie'},
            {value: 'MDA', label: 'Moldavsko'},
            {value: 'MCO', label: 'Monako'},
            {value: 'MNG', label: 'Mongolsko'},
            {value: 'MOZ', label: 'Mosambik'},
            {value: 'MMR', label: 'Myanmar (Barma)'},
            {value: 'NAM', label: 'Namibie'},
            {value: 'NRU', label: 'Nauru'},
            {value: 'DEU', label: 'Německo'},
            {value: 'NPL', label: 'Nepál'},
            {value: 'NER', label: 'Niger'},
            {value: 'NGA', label: 'Nigérie'},
            {value: 'NIC', label: 'Nikaragua'},
            {value: 'NLD', label: 'Nizozemsko'},
            {value: 'NOR', label: 'Norsko'},
            {value: 'NZL', label: 'Nový Zéland'},
            {value: 'OMN', label: 'Omán'},
            {value: 'PAK', label: 'Pákistán'},
            {value: 'PLW', label: 'Palau'},
            {value: 'PAN', label: 'Panama'},
            {value: 'PNG', label: 'Papua-Nová Guinea'},
            {value: 'PRY', label: 'Paraguay'},
            {value: 'PER', label: 'Peru'},
            {value: 'CIV', label: 'Pobřeží slonoviny'},
            {value: 'POL', label: 'Polsko'},
            {value: 'PRI', label: 'Portoriko'},
            {value: 'PRT', label: 'Portugalsko'},
            {value: 'AUT', label: 'Rakousko'},
            {value: 'GNQ', label: 'Rovníková Guinea'},
            {value: 'ROU', label: 'Rumunsko'},
            {value: 'RUS', label: 'Rusko (evropská část)'},
            {value: 'RUA', label: 'Rusko (asijská část)'},
            {value: 'RWA', label: 'Rwanda'},
            {value: 'GRC', label: 'Řecko'},
            {value: 'SLV', label: 'Salvador'},
            {value: 'WSM', label: 'Samoa'},
            {value: 'SMR', label: 'San Marino'},
            {value: 'SAU', label: 'Saúdská Arábie'},
            {value: 'SEN', label: 'Senegal'},
            {value: 'PRK', label: 'Severní Korea'},
            {value: 'SYC', label: 'Seychely'},
            {value: 'SLE', label: 'Sierra Leone'},
            {value: 'SGP', label: 'Singapur'},
            {value: 'SVK', label: 'Slovensko'},
            {value: 'SVN', label: 'Slovinsko'},
            {value: 'SOM', label: 'Somálsko'},
            {value: 'ARE', label: 'Spojené arabské emiráty'},
            {value: 'GBR', label: 'Spojené království'},
            {value: 'USA', label: 'USA'},
            {value: 'SRB', label: 'Srbsko'},
            {value: 'CAF', label: 'Středoafrická republika'},
            {value: 'SDN', label: 'Súdán'},
            {value: 'SUR', label: 'Surinam'},
            {value: 'LCA', label: 'Svatá Lucie'},
            {value: 'KNA', label: 'Svatý Kryštof a Nevis'},
            {value: 'STP', label: 'Svatý Tomáš a Princův ostrov'},
            {value: 'VCT', label: 'Svatý Vincenc a Grenadiny'},
            {value: 'SWZ', label: 'Svazijsko'},
            {value: 'SYR', label: 'Sýrie'},
            {value: 'SLB', label: 'Šalamounovy ostrovy'},
            {value: 'ESP', label: 'Španělsko'},
            {value: 'LKA', label: 'Šrí Lanka'},
            {value: 'SWE', label: 'Švédsko'},
            {value: 'CHE', label: 'Švýcarsko'},
            {value: 'TJK', label: 'Tádžikistán'},
            {value: 'TZA', label: 'Tanzanie'},
            {value: 'THA', label: 'Thajsko'},
            {value: 'TWN', label: 'Tchaj-wan'},
            {value: 'TGO', label: 'Togo'},
            {value: 'TON', label: 'Tonga'},
            {value: 'TTO', label: 'Trinidad a Tobago'},
            {value: 'TUN', label: 'Tunisko'},
            {value: 'TUR', label: 'Turecko'},
            {value: 'TKM', label: 'Turkmenistán'},
            {value: 'TUV', label: 'Tuvalu'},
            {value: 'UGA', label: 'Uganda'},
            {value: 'UKR', label: 'Ukrajina'},
            {value: 'URY', label: 'Uruguay'},
            {value: 'UZB', label: 'Uzbekistán'},
            {value: 'VUT', label: 'Vanuatu'},
            {value: 'VAT', label: 'Vatikán'},
            {value: 'VEN', label: 'Venezuela'},
            {value: 'VNM', label: 'Vietnam'},
            {value: 'TLS', label: 'Východní Timor'},
            {value: 'ZMB', label: 'Zambie'},
            {value: 'ZWE', label: 'Zimbabwe'}
        ]
    }
];
